apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-certs-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi
